server:
  port: 9002
  
eureka:
  instance:
    hostname: localhost
    
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
          - Path=/user/**
        - id: contact-service
          uri: lb://account-service
          predicates:
          - Path=/account/**  
  